---
name: "rscp2mqtt"
description: "Bridge between an E3/DC pv inverter device and a MQTT broker"
version: "0.0.37"
slug: "rscp2mqtt"
init: false
services:
  - "mqtt:need"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/goebelmeier/ha-addons/tree/main/rscp2mqtt"
startup: "services"
options:
  e3dc_ip: null
  e3dc_port: 5033
  e3dc_user: null
  e3dc_password: null
  e3dc_aes_password: null
  mqtt_qos: 0
  mqtt_retain: false
  logfile: ""
  interval: 1
  pvi_requests: true
  pvi_tracker: 2
  pm_requests: true
  auto_refresh: false
  dryrun: false
schema:
  e3dc_ip: str
  e3dc_port: port
  e3dc_user: str
  e3dc_password: password
  e3dc_aes_password: password
  mqtt_qos: "int(0,2)"
  mqtt_retain: bool
  logfile: "str?"
  interval: "int(1,10)"
  pvi_requests: bool
  pvi_tracker: "int(1,2)"
  pm_requests: bool
  auto_refresh: bool
  dryrun: bool
